name: Update Economic Indicator Data

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Paso 1 - Checkout repo
        uses: actions/checkout@v4

      - name: Paso 2 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.2"

      - name: Paso 3 - Crear entorno virtual
        run: python -m venv venv

      - name: Paso 4 - Activar entorno virtual
        run: ./venv/Scripts/activate

      - name: Paso 5 - Actualizar pip
        run: pip install --upgrade pip

      - name: Paso 6 - Instalar dependencias específicas
        run: |
          pip install pandas
          pip install yfinance
          pip install requests
          pip install beautifulsoup4          
          pip install -r src/project_piv/requirements.txt

      - name: Paso 7 - Ejecutar Script
        run: |
          python src/project_piv/main.py          
          python src/project_piv/enricher.py

      - name: Paso 8 - Commit y Push de cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Actualización automática de datos del E-Mini S&P 500
          commit_user_name: Omar Aleiser Alvarez [GitHub Actions]
          commit_user_email: omar.alvarez@iudigital.edu.co
          commit_author: Omar Alvarez <omar.alvarez@iudigital.edu.co>
          # specific files to commit
          file_pattern: "src/project_piv/static/data/* src/project_piv/logs/*"
